version: '2.4'

services:

  api:
    build: .docker/php/.
    container_name: php_api
    ports:
      - "8002:80"
    volumes:
      - ./php_api:/var/www/html
    networks:
      - app

  db:
    build: .docker/mysql/.
    container_name: db
    restart: always
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: A_1234567
      MYSQL_DATABASE: db_match_project
      MYSQL_USER: math
      MYSQL_PASSWORD: math2022
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin
    container_name: myadmin
    restart: always
    ports:
      - 8088:80
    networks:
      - app

  backend:
    build: .docker/php/.
    container_name: api
    ports:
      - "8000:80"
    volumes:
      - ./CrudSynfonySolid:/var/www/html
    networks:
      - app

 
networks:
  app:
    driver: bridge